<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Kuesioner</title>
	<link rel="stylesheet" type="text/css" href="{{asset('css/view.css')}}" media="all">
	<script type="text/javascript" src="{{asset('js/view.js')}}"></script>
</head>
<body id="main_body" >
	<img id="top" src="{{asset('images/top.png')}}" alt="">
	<div id="form_container">
		<h1><a>OSN Astronomi 2015</a></h1>
		<form id="form_1012104" class="appnitro"  method="post" role="form" action="">
			<div class="form_description">
				<h2>Kuesioner</h2>
				<p></p>
			</div>						
			<ul >
				<li id="li_1" >
					<label class="description" for="element_1">Masukkan username anda </label>
					<div>
						<input required id="element_1" name="username" class="element text medium" type="text" maxlength="255" value=""/> 
					</div> 
				</li>		
				<li id="li_2" >
					<label class="description" for="element_2">Paragraph </label>
					<div>
						<textarea id="element_2" name="jawaban1" class="element textarea medium"></textarea> 
					</div> 
				</li>		
				<li id="li_3" >
					<label class="description" for="element_3">Paragraph </label>
					<div>
						<textarea id="element_3" name="jawaban2" class="element textarea medium"></textarea> 
					</div> 
				</li>
				<li id="li_4" >
					<label class="description" for="element_4">Paragraph </label>
					<div>
						<textarea id="element_4" name="jawaban3" class="element textarea medium"></textarea> 
					</div> 
				</li>
				<li id="li_5" >
					<label class="description" for="element_5">Paragraph </label>
					<div>
						<textarea id="element_5" name="jawaban4" class="element textarea medium"></textarea> 
					</div> 
				</li>
				<li id="li_6" >
					<label class="description" for="element_6">Paragraph </label>
					<div>
						<textarea id="element_6" name="jawaban5" class="element textarea medium"></textarea> 
					</div> 
				</li>
				<li class="buttons">
				    <input type="hidden" name="form_id" value="1012104" />
					<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
				</li>
			</ul>
		</form>	
<!-- 		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div> -->
	</div>
	<img id="bottom" src="{{asset('images/bottom.png')}}" alt="">
	</body>
</html>